{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Untitled","provenance":[],"collapsed_sections":[],"toc_visible":true},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"TPU"},"cells":[{"cell_type":"code","metadata":{"id":"70-riBj15Np_","colab_type":"code","outputId":"85547da9-0159-42b1-df54-a5cc4b16bd1e","executionInfo":{"status":"ok","timestamp":1585785093827,"user_tz":240,"elapsed":33163,"user":{"displayName":"Mahmoud Abou Nassif","photoUrl":"","userId":"12855735478414363459"}},"colab":{"base_uri":"https://localhost:8080/","height":124}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly\n","\n","Enter your authorization code:\n","··········\n","Mounted at /content/drive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Gvkf2NtYUnga","colab_type":"code","outputId":"45c601b5-9cca-4ef3-fae3-bda601cb9809","executionInfo":{"status":"ok","timestamp":1585785161139,"user_tz":240,"elapsed":315,"user":{"displayName":"Mahmoud Abou Nassif","photoUrl":"","userId":"12855735478414363459"}},"colab":{"base_uri":"https://localhost:8080/","height":35}},"source":["import os\n","os.chdir(os.path.join('drive', 'My Drive', 'ift6759', 'ift6759-t6-p2'))\n","os.getcwd()"],"execution_count":3,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'/content/drive/My Drive/ift6759/ift6759-t6-p2'"]},"metadata":{"tags":[]},"execution_count":3}]},{"cell_type":"code","metadata":{"id":"Qzzy3rwtU8Fl","colab_type":"code","outputId":"20ea866d-64fc-4e02-af2b-1ea5db60cea7","executionInfo":{"status":"ok","timestamp":1585785164858,"user_tz":240,"elapsed":1032,"user":{"displayName":"Mahmoud Abou Nassif","photoUrl":"","userId":"12855735478414363459"}},"colab":{"base_uri":"https://localhost:8080/","height":52}},"source":["!nvidia-smi"],"execution_count":4,"outputs":[{"output_type":"stream","text":["NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"X2-RDyFC5gEU","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":435},"outputId":"77015c3f-5c93-4a6f-e1d8-d3d00f9606b4","executionInfo":{"status":"ok","timestamp":1585785179318,"user_tz":240,"elapsed":11615,"user":{"displayName":"Mahmoud Abou Nassif","photoUrl":"","userId":"12855735478414363459"}}},"source":["!python train_language_model2.py"],"execution_count":5,"outputs":[{"output_type":"stream","text":["2020-04-01 23:47:46.611891: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc2\n","Running on TPU  ['10.25.207.50:8470']\n","2020-04-01 23:47:49.879029: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-04-01 23:47:49.925065: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-04-01 23:47:49.925139: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (348b56ab0261): /proc/driver/nvidia/version does not exist\n","2020-04-01 23:47:49.960608: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-04-01 23:47:49.960855: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1818f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-04-01 23:47:49.960891: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-04-01 23:47:50.009636: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.25.207.50:8470}\n","2020-04-01 23:47:50.009690: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30348}\n","2020-04-01 23:47:50.032058: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.25.207.50:8470}\n","2020-04-01 23:47:50.032115: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30348}\n","2020-04-01 23:47:50.032846: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:30348\n","data_file: data/unaligned_unformated_fr , tokenize_type: c , remove_punctuation: True\n","Traceback (most recent call last):\n","  File \"train_language_model2.py\", line 56, in <module>\n","    remove_punctuation=remove_punctuation)\n","  File \"/content/drive/My Drive/ift6759/ift6759-t6-p2/utils/data.py\", line 37, in preprocessing\n","    lines = f.readlines()\n","  File \"/usr/lib/python3.6/codecs.py\", line 318, in decode\n","    def decode(self, input, final=False):\n","KeyboardInterrupt\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"vXvyWnn95Gis","colab_type":"code","colab":{}},"source":["!python train_language_model1.py"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"r-guA1E4U4ZU","colab_type":"code","outputId":"a4804042-95d5-443c-ac2c-ea6dd3f16384","executionInfo":{"status":"ok","timestamp":1585479179693,"user_tz":240,"elapsed":133349,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!python train_language_model.py"],"execution_count":0,"outputs":[{"output_type":"stream","text":["2020-03-29 10:18:20.671291: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc1\n","Running on TPU  ['10.102.29.130:8470']\n","2020-03-29 10:18:22.903738: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-03-29 10:18:22.905703: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-03-29 10:18:22.905749: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (977c666240d7): /proc/driver/nvidia/version does not exist\n","2020-03-29 10:18:22.912069: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-03-29 10:18:22.912286: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f84f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-03-29 10:18:22.912319: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-03-29 10:18:22.917605: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.102.29.130:8470}\n","2020-03-29 10:18:22.917699: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:35379}\n","2020-03-29 10:18:22.934006: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.102.29.130:8470}\n","2020-03-29 10:18:22.934051: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:35379}\n","2020-03-29 10:18:22.934517: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:35379\n","data_file: data/unaligned_unformated_eng , tokenize_type: w , remove_punctuation: True\n","100% 474000/474000 [00:04<00:00, 116882.25it/s]\n","Epoch 1/20\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - ETA: 0s - loss: 0.8767WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","2020-03-29 10:21:18.534165: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 286273536 exceeds 10% of free system memory.\n","2020-03-29 10:21:21.808929: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 286273536 exceeds 10% of free system memory.\n","2020-03-29 10:21:22.728681: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 286273536 exceeds 10% of free system memory.\n","500/500 [==============================] - 101s 203ms/step - loss: 0.8767 - val_loss: 0.6650\n","Epoch 2/20\n","500/500 [==============================] - ETA: 0s - loss: 0.6538WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","2020-03-29 10:22:59.266463: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 286273536 exceeds 10% of free system memory.\n","2020-03-29 10:23:03.460231: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 286273536 exceeds 10% of free system memory.\n","500/500 [==============================] - 100s 201ms/step - loss: 0.6538 - val_loss: 0.6201\n","Epoch 3/20\n","500/500 [==============================] - ETA: 0s - loss: 0.6083WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 98s 197ms/step - loss: 0.6083 - val_loss: 0.5931\n","Epoch 4/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5986WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5986 - val_loss: 0.5807\n","Epoch 5/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5757WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 100s 200ms/step - loss: 0.5757 - val_loss: 0.5637\n","Epoch 6/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5624WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5624 - val_loss: 0.5535\n","Epoch 7/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5501WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 100s 200ms/step - loss: 0.5501 - val_loss: 0.5452\n","Epoch 8/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5456WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 199ms/step - loss: 0.5456 - val_loss: 0.5380\n","Epoch 9/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5370WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5370 - val_loss: 0.5318\n","Epoch 10/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5290WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 98s 197ms/step - loss: 0.5290 - val_loss: 0.5256\n","Epoch 11/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5273WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5273 - val_loss: 0.5202\n","Epoch 12/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5189WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 197ms/step - loss: 0.5189 - val_loss: 0.5149\n","Epoch 13/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5147WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5147 - val_loss: 0.5111\n","Epoch 14/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5119WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5119 - val_loss: 0.5071\n","Epoch 15/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5062WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 98s 197ms/step - loss: 0.5062 - val_loss: 0.4930\n","Epoch 16/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5027WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 199ms/step - loss: 0.5027 - val_loss: 0.4546\n","Epoch 17/20\n","500/500 [==============================] - ETA: 0s - loss: 0.5000WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.5000 - val_loss: 0.4611\n","Epoch 18/20\n","500/500 [==============================] - ETA: 0s - loss: 0.4925WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 98s 197ms/step - loss: 0.4925 - val_loss: 0.4633\n","Epoch 19/20\n","500/500 [==============================] - ETA: 0s - loss: 0.4903WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 98s 196ms/step - loss: 0.4903 - val_loss: 0.4644\n","Epoch 20/20\n","500/500 [==============================] - ETA: 0s - loss: 0.4896WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 181).\n","500/500 [==============================] - 99s 198ms/step - loss: 0.4896 - val_loss: 0.4645\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"GAEK7k0A64Zr","colab_type":"code","outputId":"3b173955-889c-4282-d19e-995aca831ce6","executionInfo":{"status":"ok","timestamp":1585483469487,"user_tz":240,"elapsed":4091528,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!python train_language_model3.py"],"execution_count":0,"outputs":[{"output_type":"stream","text":["2020-03-29 10:56:18.628196: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc1\n","Running on TPU  ['10.7.67.10:8470']\n","2020-03-29 10:56:20.796525: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-03-29 10:56:20.798300: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-03-29 10:56:20.798346: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (44b45547aac6): /proc/driver/nvidia/version does not exist\n","2020-03-29 10:56:20.805246: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-03-29 10:56:20.805444: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2068f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-03-29 10:56:20.805477: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-03-29 10:56:20.811031: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.7.67.10:8470}\n","2020-03-29 10:56:20.811066: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30451}\n","2020-03-29 10:56:20.824268: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.7.67.10:8470}\n","2020-03-29 10:56:20.824306: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30451}\n","2020-03-29 10:56:20.824772: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:30451\n","data_file: data/unaligned_formated_fr , tokenize_type: c , remove_punctuation: False\n","100% 474000/474000 [00:07<00:00, 66171.04it/s]\n","tcmalloc: large alloc 1841020928 bytes == 0x64dbe000 @  0x7f933a0141e7 0x7f93374515e1 0x7f93374b5e88 0x7f93374b6147 0x7f933754e118 0x50ac25 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50b403 0x635222 0x6352d7 0x638a8f 0x639631 0x4b0f40 0x7f9339c11b97\n","tcmalloc: large alloc 1841020928 bytes == 0xd297e000 @  0x7f933a016887 0x7f933890cc39 0x7f933890d002 0x7f933890d66e 0x7f92fde5b8fc 0x7f93024af88b 0x7f93024b3a33 0x7f93024d1116 0x7f93024d166d 0x7f930249f26a 0x7f9302068089 0x7f9301cf2387 0x7f9301cf37e4 0x551b81 0x5aa6ec 0x50abb3 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080\n","Epoch 1/20\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - ETA: 0s - loss: 0.3652WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.3652 - val_loss: 0.2549\n","Epoch 2/20\n","500/500 [==============================] - ETA: 0s - loss: 0.2204WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 402ms/step - loss: 0.2204 - val_loss: 0.1891\n","Epoch 3/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1699WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 203s 406ms/step - loss: 0.1699 - val_loss: 0.1559\n","Epoch 4/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1482WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 202s 404ms/step - loss: 0.1482 - val_loss: 0.1411\n","Epoch 5/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1368WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1368 - val_loss: 0.1331\n","Epoch 6/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1306WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 202s 403ms/step - loss: 0.1306 - val_loss: 0.1281\n","Epoch 7/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1262WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1262 - val_loss: 0.1245\n","Epoch 8/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1233WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1233 - val_loss: 0.1219\n","Epoch 9/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1211WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 202s 403ms/step - loss: 0.1211 - val_loss: 0.1199\n","Epoch 10/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1187WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1187 - val_loss: 0.1180\n","Epoch 11/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1171WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1171 - val_loss: 0.1169\n","Epoch 12/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1165WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 402ms/step - loss: 0.1165 - val_loss: 0.1156\n","Epoch 13/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1148WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 402ms/step - loss: 0.1148 - val_loss: 0.1147\n","Epoch 14/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1143WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1143 - val_loss: 0.1139\n","Epoch 15/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1135WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1135 - val_loss: 0.1114\n","Epoch 16/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1127WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1127 - val_loss: 0.1087\n","Epoch 17/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1117WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1117 - val_loss: 0.1098\n","Epoch 18/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1116WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 402ms/step - loss: 0.1116 - val_loss: 0.1096\n","Epoch 19/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1113WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 202s 403ms/step - loss: 0.1113 - val_loss: 0.1096\n","Epoch 20/20\n","500/500 [==============================] - ETA: 0s - loss: 0.1107WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 970).\n","500/500 [==============================] - 201s 403ms/step - loss: 0.1107 - val_loss: 0.1094\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"1MrKu9UOZUfY","colab_type":"code","colab":{}},"source":["import tensorflow as tf\n","checkpoint_dir = 'language_models/unformated_eng_w2w/'\n","checkpoint_prefix = os.path.join(os.getcwd(),checkpoint_dir,\"GRU_{epoch}.h5\")\n","tf.train.latest_checkpoint(os.path.join(os.getcwd(),checkpoint_dir))"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"bYcBOGGqkNJR","colab_type":"code","colab":{}},"source":["def build_model(vocab_size, embedding_dim, rnn_units, batch_size):\n","  model = tf.keras.Sequential([\n","    tf.keras.layers.Embedding(vocab_size, embedding_dim,\n","                              batch_input_shape=[batch_size, None]),\n","    tf.keras.layers.GRU(rnn_units,\n","                        return_sequences=True,\n","                        stateful=True,\n","                        recurrent_initializer='glorot_uniform'),\n","    tf.keras.layers.Dense(vocab_size)\n","  ])\n","  return model\n","\n","model = build_model(vocab_size=63132, embedding_dim=256, rnn_units=1024, batch_size=1)\n","model.load_weights(os.path.join(os.getcwd(),checkpoint_dir, \"GRU_10.h5\"))\n","model.build(tf.TensorShape([1, None]))"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"TMjghHrmknZo","colab_type":"code","outputId":"dac28aa6-97cd-419b-95e2-39ba7b080fd9","executionInfo":{"status":"ok","timestamp":1585473816313,"user_tz":240,"elapsed":16708,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":255}},"source":["model.summary()"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Model: \"sequential\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","embedding (Embedding)        (1, None, 256)            16161792  \n","_________________________________________________________________\n","gru (GRU)                    (1, None, 1024)           3938304   \n","_________________________________________________________________\n","dense (Dense)                (1, None, 63132)          64710300  \n","=================================================================\n","Total params: 84,810,396\n","Trainable params: 84,810,396\n","Non-trainable params: 0\n","_________________________________________________________________\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"KCKmPo_nmVJN","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]}]}