{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"train_language_model.ipynb","provenance":[],"collapsed_sections":[],"toc_visible":true},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"TPU"},"cells":[{"cell_type":"code","metadata":{"id":"70-riBj15Np_","colab_type":"code","outputId":"73acb148-d47b-41a7-f4db-ce357857f028","executionInfo":{"status":"ok","timestamp":1586040189064,"user_tz":240,"elapsed":21932,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":122}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly\n","\n","Enter your authorization code:\n","··········\n","Mounted at /content/drive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Gvkf2NtYUnga","colab_type":"code","outputId":"4110fbdc-3694-4f62-f9bc-411ce3d67004","executionInfo":{"status":"ok","timestamp":1586040189071,"user_tz":240,"elapsed":4153,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":34}},"source":["import os\n","os.chdir(os.path.join('drive', 'My Drive', 'ift6759', 'ift6759-t6-p2'))\n","os.getcwd()"],"execution_count":2,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'/content/drive/My Drive/ift6759/ift6759-t6-p2'"]},"metadata":{"tags":[]},"execution_count":2}]},{"cell_type":"code","metadata":{"id":"Qzzy3rwtU8Fl","colab_type":"code","outputId":"12e91cae-2e00-4500-a20b-90bd655f74a0","executionInfo":{"status":"ok","timestamp":1585986272462,"user_tz":240,"elapsed":16059,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":71}},"source":["!nvidia-smi"],"execution_count":0,"outputs":[{"output_type":"stream","text":["NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"X2-RDyFC5gEU","colab_type":"code","outputId":"f74e09fa-f859-4702-9005-3360210f3569","executionInfo":{"status":"ok","timestamp":1586041006539,"user_tz":240,"elapsed":497771,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!python train_language_model.py --task unformated_en_w2w --epochs 30 --batch_size 128"],"execution_count":4,"outputs":[{"output_type":"stream","text":["2020-04-04 22:47:01.446071: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc2\n","2020-04-04 22:47:03.632569: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-04-04 22:47:03.634494: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-04-04 22:47:03.634552: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0e82103ff3d3): /proc/driver/nvidia/version does not exist\n","2020-04-04 22:47:03.641427: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-04-04 22:47:03.641685: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x22d2f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-04-04 22:47:03.641724: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-04-04 22:47:03.647849: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.27.128.242:8470}\n","2020-04-04 22:47:03.647890: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30475}\n","2020-04-04 22:47:03.663993: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.27.128.242:8470}\n","2020-04-04 22:47:03.664038: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30475}\n","2020-04-04 22:47:03.664532: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:30475\n","Running on TPU  ['10.27.128.242:8470']\n","data_file:data/unaligned_unformated_en, tokenize_type:w, rm_punc:True\n","100% 474000/474000 [00:03<00:00, 133019.01it/s]\n","\n","# v2id dictionary saved at: /content/drive/My Drive/ift6759/ift6759-t6-p2/language_models/unformated_en_w2w/v2id.json\n","Epoch 1/30\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","498/500 [============================>.] - ETA: 0s - loss: 3.4200WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 37ms/step - loss: 3.4161 - val_loss: 2.5519\n","Epoch 2/30\n","498/500 [============================>.] - ETA: 0s - loss: 2.4677WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 19s 39ms/step - loss: 2.4676 - val_loss: 2.3838\n","Epoch 3/30\n","498/500 [============================>.] - ETA: 0s - loss: 2.3220WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 19s 38ms/step - loss: 2.3212 - val_loss: 2.2583\n","Epoch 4/30\n","500/500 [==============================] - ETA: 0s - loss: 2.2138WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 19s 39ms/step - loss: 2.2138 - val_loss: 2.1783\n","Epoch 5/30\n","499/500 [============================>.] - ETA: 0s - loss: 2.1417WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 37ms/step - loss: 2.1417 - val_loss: 2.1216\n","Epoch 6/30\n","499/500 [============================>.] - ETA: 0s - loss: 2.1008WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 37ms/step - loss: 2.1007 - val_loss: 2.0786\n","Epoch 7/30\n","499/500 [============================>.] - ETA: 0s - loss: 2.0613WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 19s 37ms/step - loss: 2.0615 - val_loss: 2.0451\n","Epoch 8/30\n","499/500 [============================>.] - ETA: 0s - loss: 2.0291WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 37ms/step - loss: 2.0291 - val_loss: 1.9801\n","Epoch 9/30\n","499/500 [============================>.] - ETA: 0s - loss: 2.0027WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 19s 38ms/step - loss: 2.0029 - val_loss: 1.9495\n","Epoch 10/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.9831WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 19s 38ms/step - loss: 1.9830 - val_loss: 1.9406\n","Epoch 11/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.9563WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 35ms/step - loss: 1.9566 - val_loss: 1.9302\n","Epoch 12/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.9391WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.9390 - val_loss: 1.9203\n","Epoch 13/30\n","500/500 [==============================] - ETA: 0s - loss: 1.9292WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.9292 - val_loss: 1.9104\n","Epoch 14/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.9063WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.9063 - val_loss: 1.9031\n","Epoch 15/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8989WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8989 - val_loss: 1.8782\n","Epoch 16/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8891WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8889 - val_loss: 1.8220\n","Epoch 17/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.8703WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8705 - val_loss: 1.8299\n","Epoch 18/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8661WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8661 - val_loss: 1.8313\n","Epoch 19/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.8511WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 34ms/step - loss: 1.8509 - val_loss: 1.8307\n","Epoch 20/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8448WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8454 - val_loss: 1.8292\n","Epoch 21/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8356WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 34ms/step - loss: 1.8356 - val_loss: 1.8275\n","Epoch 22/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.8315WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8316 - val_loss: 1.8255\n","Epoch 23/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8197WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.8197 - val_loss: 1.7625\n","Epoch 24/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8146WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 35ms/step - loss: 1.8147 - val_loss: 1.7636\n","Epoch 25/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8103WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 18s 35ms/step - loss: 1.8100 - val_loss: 1.7708\n","Epoch 26/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8008WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 34ms/step - loss: 1.8003 - val_loss: 1.7751\n","Epoch 27/30\n","500/500 [==============================] - ETA: 0s - loss: 1.7942WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.7942 - val_loss: 1.7769\n","Epoch 28/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.7910WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 34ms/step - loss: 1.7905 - val_loss: 1.7782\n","Epoch 29/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.7826WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.7827 - val_loss: 1.7794\n","Epoch 30/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.7830WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 17s 35ms/step - loss: 1.7830 - val_loss: 1.7469\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"i0Qh54ia5oTC","colab_type":"code","outputId":"ba548ac6-2b48-4ab6-b222-773789e4bc15","executionInfo":{"status":"ok","timestamp":1586041704064,"user_tz":240,"elapsed":697534,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!python train_language_model.py --task unformated_fr_w2w --epochs 30 --batch_size 128"],"execution_count":5,"outputs":[{"output_type":"stream","text":["2020-04-04 22:56:52.603352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc2\n","2020-04-04 22:56:54.994069: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-04-04 22:56:54.995982: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-04-04 22:56:54.996024: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0e82103ff3d3): /proc/driver/nvidia/version does not exist\n","2020-04-04 22:56:55.002167: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-04-04 22:56:55.002386: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ee0f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-04-04 22:56:55.002418: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-04-04 22:56:55.007947: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.27.128.242:8470}\n","2020-04-04 22:56:55.007983: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30618}\n","2020-04-04 22:56:55.022278: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.27.128.242:8470}\n","2020-04-04 22:56:55.022310: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30618}\n","2020-04-04 22:56:55.022748: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:30618\n","Running on TPU  ['10.27.128.242:8470']\n","data_file:data/unaligned_unformated_fr, tokenize_type:w, rm_punc:True\n","100% 474000/474000 [00:04<00:00, 111044.39it/s]\n","\n","# v2id dictionary saved at: /content/drive/My Drive/ift6759/ift6759-t6-p2/language_models/unformated_fr_w2w/v2id.json\n","Epoch 1/30\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","499/500 [============================>.] - ETA: 0s - loss: 3.7710WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 23s 45ms/step - loss: 3.7692 - val_loss: 2.8493\n","Epoch 2/30\n","500/500 [==============================] - ETA: 0s - loss: 2.7372WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 44ms/step - loss: 2.7372 - val_loss: 2.5991\n","Epoch 3/30\n","500/500 [==============================] - ETA: 0s - loss: 2.5056WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 43ms/step - loss: 2.5056 - val_loss: 2.3919\n","Epoch 4/30\n","500/500 [==============================] - ETA: 0s - loss: 2.3332WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 43ms/step - loss: 2.3332 - val_loss: 2.2660\n","Epoch 5/30\n","500/500 [==============================] - ETA: 0s - loss: 2.2324WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 44ms/step - loss: 2.2324 - val_loss: 2.1889\n","Epoch 6/30\n","500/500 [==============================] - ETA: 0s - loss: 2.1680WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 21s 43ms/step - loss: 2.1680 - val_loss: 2.1342\n","Epoch 7/30\n","499/500 [============================>.] - ETA: 0s - loss: 2.1167WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 44ms/step - loss: 2.1165 - val_loss: 2.0942\n","Epoch 8/30\n","500/500 [==============================] - ETA: 0s - loss: 2.0825WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 23s 46ms/step - loss: 2.0825 - val_loss: 2.0143\n","Epoch 9/30\n","500/500 [==============================] - ETA: 0s - loss: 2.0468WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 44ms/step - loss: 2.0468 - val_loss: 1.9768\n","Epoch 10/30\n","500/500 [==============================] - ETA: 0s - loss: 2.0238WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 22s 43ms/step - loss: 2.0238 - val_loss: 1.9655\n","Epoch 11/30\n","500/500 [==============================] - ETA: 0s - loss: 1.9956WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.9956 - val_loss: 1.9534\n","Epoch 12/30\n","500/500 [==============================] - ETA: 0s - loss: 1.9737WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 21s 42ms/step - loss: 1.9737 - val_loss: 1.9427\n","Epoch 13/30\n","500/500 [==============================] - ETA: 0s - loss: 1.9553WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.9553 - val_loss: 1.9313\n","Epoch 14/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.9392WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.9395 - val_loss: 1.9228\n","Epoch 15/30\n","500/500 [==============================] - ETA: 0s - loss: 1.9233WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.9233 - val_loss: 1.8952\n","Epoch 16/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.9094WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 21s 41ms/step - loss: 1.9089 - val_loss: 1.8296\n","Epoch 17/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8995WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8995 - val_loss: 1.8381\n","Epoch 18/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8837WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8837 - val_loss: 1.8393\n","Epoch 19/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8731WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 21s 42ms/step - loss: 1.8736 - val_loss: 1.8385\n","Epoch 20/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.8561WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8557 - val_loss: 1.8365\n","Epoch 21/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.8566WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8565 - val_loss: 1.8348\n","Epoch 22/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8376WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8376 - val_loss: 1.8332\n","Epoch 23/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8373WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 21s 41ms/step - loss: 1.8373 - val_loss: 1.7601\n","Epoch 24/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8274WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8274 - val_loss: 1.7614\n","Epoch 25/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.8197WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8200 - val_loss: 1.7701\n","Epoch 26/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8111WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 21s 42ms/step - loss: 1.8111 - val_loss: 1.7750\n","Epoch 27/30\n","500/500 [==============================] - ETA: 0s - loss: 1.8047WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.8047 - val_loss: 1.7775\n","Epoch 28/30\n","500/500 [==============================] - ETA: 0s - loss: 1.7972WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.7972 - val_loss: 1.7805\n","Epoch 29/30\n","498/500 [============================>.] - ETA: 0s - loss: 1.7914WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 41ms/step - loss: 1.7910 - val_loss: 1.7813\n","Epoch 30/30\n","499/500 [============================>.] - ETA: 0s - loss: 1.7858WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","WARNING:tensorflow:Model was constructed with shape (128, None) for input Tensor(\"embedding_input:0\", shape=(128, None), dtype=float32), but it was called on an input with incompatible shape (16, 49).\n","500/500 [==============================] - 20s 40ms/step - loss: 1.7859 - val_loss: 1.7431\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"60naHt9_5oFz","colab_type":"code","outputId":"9af35297-2876-4eb9-c4f8-282e65c8b777","executionInfo":{"status":"ok","timestamp":1585988807931,"user_tz":240,"elapsed":2443910,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":785}},"source":["!python train_language_model.py --task unformated_fr_c2c --epochs 5"],"execution_count":0,"outputs":[{"output_type":"stream","text":["2020-04-04 08:08:31.967303: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc2\n","2020-04-04 08:08:37.700074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-04-04 08:08:37.703038: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-04-04 08:08:37.703105: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a1fcd3eaed5c): /proc/driver/nvidia/version does not exist\n","2020-04-04 08:08:37.710422: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-04-04 08:08:37.710711: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1638f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-04-04 08:08:37.710750: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-04-04 08:08:37.721831: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.96.99.34:8470}\n","2020-04-04 08:08:37.721928: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:32167}\n","2020-04-04 08:08:37.739233: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.96.99.34:8470}\n","2020-04-04 08:08:37.739598: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:32167}\n","2020-04-04 08:08:37.741806: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:32167\n","Running on TPU  ['10.96.99.34:8470']\n","data_file:data/unaligned_unformated_fr, tokenize_type:c, rm_punc:True\n","100% 474000/474000 [00:10<00:00, 45741.74it/s]\n","tcmalloc: large alloc 1844813824 bytes == 0x5f72a000 @  0x7f17d8b981e7 0x7f17d5fd55e1 0x7f17d6039e88 0x7f17d603a147 0x7f17d60d2118 0x50ac25 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x509d48 0x50aa7d 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x58958c 0x5a067e 0x50d966 0x508245\n","\n","# v2id dictionary saved at: /content/drive/My Drive/ift6759/ift6759-t6-p2/language_models/unformated_fr_c2c/v2id.json\n","tcmalloc: large alloc 1844813824 bytes == 0xcde84000 @  0x7f17d8b9a887 0x7f17d7490c39 0x7f17d7491002 0x7f17d749166e 0x7f179c9df8fc 0x7f17a103388b 0x7f17a1037a33 0x7f17a1055116 0x7f17a105566d 0x7f17a102326a 0x7f17a0bec089 0x7f17a0876387 0x7f17a08777e4 0x551b81 0x5aa6ec 0x50abb3 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080\n","Epoch 1/5\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","500/500 [==============================] - ETA: 0s - loss: 0.4099WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","500/500 [==============================] - 202s 404ms/step - loss: 0.4099 - val_loss: 0.2675\n","Epoch 2/5\n","500/500 [==============================] - ETA: 0s - loss: 0.2391WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","500/500 [==============================] - 202s 404ms/step - loss: 0.2391 - val_loss: 0.2126\n","Epoch 3/5\n","500/500 [==============================] - ETA: 0s - loss: 0.1905WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","500/500 [==============================] - 202s 405ms/step - loss: 0.1905 - val_loss: 0.1718\n","Epoch 4/5\n","500/500 [==============================] - ETA: 0s - loss: 0.1605WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","500/500 [==============================] - 202s 404ms/step - loss: 0.1605 - val_loss: 0.1501\n","Epoch 5/5\n","500/500 [==============================] - ETA: 0s - loss: 0.1443WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","WARNING:tensorflow:Model was constructed with shape (64, None) for input Tensor(\"embedding_input:0\", shape=(64, None), dtype=float32), but it was called on an input with incompatible shape (8, 972).\n","500/500 [==============================] - 202s 404ms/step - loss: 0.1443 - val_loss: 0.1394\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"aOd8rCxK5n4Z","colab_type":"code","outputId":"ae0b4e94-e143-42b4-9f86-fc86c9b17e69","executionInfo":{"status":"ok","timestamp":1585990891567,"user_tz":240,"elapsed":4515534,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":785}},"source":["!python train_language_model.py --task formated_fr_c2c --epochs 5 --batch_size 32 --steps_per_epoch 1000"],"execution_count":0,"outputs":[{"output_type":"stream","text":["2020-04-04 08:26:48.550405: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","Tensorflow version 2.2.0-rc2\n","2020-04-04 08:26:51.827530: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-04-04 08:26:51.833779: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2020-04-04 08:26:51.833836: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a1fcd3eaed5c): /proc/driver/nvidia/version does not exist\n","2020-04-04 08:26:51.841455: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-04-04 08:26:51.841770: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2364f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-04-04 08:26:51.841811: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-04-04 08:26:51.849288: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.96.99.34:8470}\n","2020-04-04 08:26:51.849330: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:32322}\n","2020-04-04 08:26:51.863916: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.96.99.34:8470}\n","2020-04-04 08:26:51.863969: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:32322}\n","2020-04-04 08:26:51.864641: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:32322\n","Running on TPU  ['10.96.99.34:8470']\n","data_file:data/unaligned_formated_fr, tokenize_type:c, rm_punc:False\n","100% 474000/474000 [00:10<00:00, 46162.16it/s]\n","tcmalloc: large alloc 1859977216 bytes == 0x63dd6000 @  0x7f43894421e7 0x7f438687f5e1 0x7f43868e3e88 0x7f43868e4147 0x7f438697c118 0x50ac25 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x509d48 0x50aa7d 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x58958c 0x5a067e 0x50d966 0x508245\n","\n","# v2id dictionary saved at: /content/drive/My Drive/ift6759/ift6759-t6-p2/language_models/formated_fr_c2c/v2id.json\n","tcmalloc: large alloc 1859977216 bytes == 0xd33a8000 @  0x7f4389444887 0x7f4387d3ac39 0x7f4387d3b002 0x7f4387d3b66e 0x7f434d2898fc 0x7f43518dd88b 0x7f43518e1a33 0x7f43518ff116 0x7f43518ff66d 0x7f43518cd26a 0x7f4351496089 0x7f4351120387 0x7f43511217e4 0x551b81 0x5aa6ec 0x50abb3 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080\n","Epoch 1/5\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","1000/1000 [==============================] - ETA: 0s - loss: 0.3250WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","1000/1000 [==============================] - 401s 401ms/step - loss: 0.3250 - val_loss: 0.2103\n","Epoch 2/5\n","1000/1000 [==============================] - ETA: 0s - loss: 0.1759WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","1000/1000 [==============================] - 401s 401ms/step - loss: 0.1759 - val_loss: 0.1543\n","Epoch 3/5\n","1000/1000 [==============================] - ETA: 0s - loss: 0.1448WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","1000/1000 [==============================] - 401s 401ms/step - loss: 0.1448 - val_loss: 0.1372\n","Epoch 4/5\n","1000/1000 [==============================] - ETA: 0s - loss: 0.1335WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","1000/1000 [==============================] - 401s 401ms/step - loss: 0.1335 - val_loss: 0.1294\n","Epoch 5/5\n","1000/1000 [==============================] - ETA: 0s - loss: 0.1270WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","WARNING:tensorflow:Model was constructed with shape (32, None) for input Tensor(\"embedding_input:0\", shape=(32, None), dtype=float32), but it was called on an input with incompatible shape (4, 980).\n","1000/1000 [==============================] - 401s 401ms/step - loss: 0.1270 - val_loss: 0.1245\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"1MrKu9UOZUfY","colab_type":"code","colab":{}},"source":["import tensorflow as tf\n","checkpoint_dir = 'language_models/unformated_eng_w2w/'\n","checkpoint_prefix = os.path.join(os.getcwd(),checkpoint_dir,\"GRU_{epoch}.h5\")\n","tf.train.latest_checkpoint(os.path.join(os.getcwd(),checkpoint_dir))"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"bYcBOGGqkNJR","colab_type":"code","colab":{}},"source":["def build_model(vocab_size, embedding_dim, rnn_units, batch_size):\n","  model = tf.keras.Sequential([\n","    tf.keras.layers.Embedding(vocab_size, embedding_dim,\n","                              batch_input_shape=[batch_size, None]),\n","    tf.keras.layers.GRU(rnn_units,\n","                        return_sequences=True,\n","                        stateful=True,\n","                        recurrent_initializer='glorot_uniform'),\n","    tf.keras.layers.Dense(vocab_size)\n","  ])\n","  return model\n","\n","model = build_model(vocab_size=63132, embedding_dim=256, rnn_units=1024, batch_size=1)\n","model.load_weights(os.path.join(os.getcwd(),checkpoint_dir, \"GRU_10.h5\"))\n","model.build(tf.TensorShape([1, None]))"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"TMjghHrmknZo","colab_type":"code","outputId":"dac28aa6-97cd-419b-95e2-39ba7b080fd9","executionInfo":{"status":"ok","timestamp":1585473816313,"user_tz":240,"elapsed":16708,"user":{"displayName":"Ankur Agarwal","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh_6W6aMEfbSSR-gH2aCHOTUvwO86Ern6Dx4xlY=s64","userId":"04283221963854590469"}},"colab":{"base_uri":"https://localhost:8080/","height":255}},"source":["model.summary()"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Model: \"sequential\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","embedding (Embedding)        (1, None, 256)            16161792  \n","_________________________________________________________________\n","gru (GRU)                    (1, None, 1024)           3938304   \n","_________________________________________________________________\n","dense (Dense)                (1, None, 63132)          64710300  \n","=================================================================\n","Total params: 84,810,396\n","Trainable params: 84,810,396\n","Non-trainable params: 0\n","_________________________________________________________________\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"KCKmPo_nmVJN","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]}]}